version: '3.8'

services:
  api:
    build: .
    container_name: smart_tradie_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GCP_PROJECT_ID=smart-tradie-dev
      - GCS_BUCKET_NAME=smart-tradie-voice-notes
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./uploaded_audio:/app/uploaded_audio
