import { WorkflowTemplate } from '../types/workflow';

export const DEFAULT_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'workflow_voice_note',
    name: 'Field Engineering Note',
    category: 'General Field Notes',
    description: 'Capture site observations, engineering audits, and actionable next steps.',
    icon: 'FileText',
    triggerPhrases: ['take note', 'new note', 'voice note', 'field note', 'note', 'add note', 'site observation'],
    steps: [
      {
        id: 'main_observation',
        name: 'Engineering Summary',
        prompt: 'Go ahead with your main note.',
        type: 'FREE_TEXT_SUMMARY',
        extractionGoal: 'Clean up filler words and provide a concise 2-sentence technical summary of this site observation.',
        placeholderFallback: 'Completed machinery inspection. System operating within safe thermal parameters.',
        required: true,
      },
      {
        id: 'followup_actions',
        name: 'Action Items Checklist',
        prompt: 'Any follow-up action items?',
        type: 'ACTION_ITEMS_CHECKLIST',
        extractionGoal: 'Extract semicolon-separated list of actionable tasks or next steps.',
        placeholderFallback: 'Order replacement seal kit; Schedule maintenance for Tuesday 8am.',
        required: false,
      },
    ],
    completionMessage: "Note saved offline. I'll sync this to Firebase when connection returns.",
    completionAction: 'SAVE_VOICE_NOTE',
  },
  {
    id: 'workflow_materials_used',
    name: 'Log Materials Used',
    category: 'Inventory & Stock',
    description: 'Deduct parts, SKUs, fittings, or consumables from company stock database.',
    icon: 'Package',
    triggerPhrases: ['materials used', 'log materials', 'log parts', 'deduct stock', 'used materials', 'parts used', 'materials', 'deduct parts'],
    steps: [
      {
        id: 'materials_list',
        name: 'Materials & Quantities',
        prompt: 'What materials did you use, and in what quantities?',
        type: 'STRUCTURED_EXTRACTION',
        extractionGoal: 'Extract list of materials with item name, quantity, and unit (e.g. 3x 50mm PVC elbows, 2 bags rapid set cement).',
        placeholderFallback: '3x 50mm PVC Elbows; 2x Bags Cement; 1x Roll Teflon Tape',
        required: true,
      },
      {
        id: 'restock_notes',
        name: 'Reorder / Restock Needed',
        prompt: 'Do you need any parts reordered for your truck?',
        type: 'FREE_TEXT_SUMMARY',
        extractionGoal: 'Summarize restock requests or replenishment items.',
        placeholderFallback: 'Restock 50mm copper couplings on van shelf 2.',
        required: false,
      },
    ],
    completionMessage: 'Materials logged offline. Stock deduction will sync to database.',
    completionAction: 'DEDUCT_MATERIALS',
  },
  {
    id: 'workflow_job_clocking',
    name: 'Time Clock & Job Travel',
    category: 'Timesheets & Payroll',
    description: 'Log job arrival, departure, travel duration, and billable labor hours.',
    icon: 'Clock',
    triggerPhrases: ['clock in', 'clock out', 'start job', 'finish job', 'log hours', 'log time', 'timesheet', 'time tracking', 'hours'],
    steps: [
      {
        id: 'clock_action',
        name: 'Clock Action',
        prompt: 'Are you clocking in to start a job, or clocking out?',
        type: 'STRUCTURED_EXTRACTION',
        extractionGoal: 'Determine if action is CLOCK_IN or CLOCK_OUT.',
        placeholderFallback: 'CLOCK_IN',
        required: true,
      },
      {
        id: 'work_scope',
        name: 'Work Done / Shift Notes',
        prompt: 'Any brief summary of work performed during this shift?',
        type: 'FREE_TEXT_SUMMARY',
        extractionGoal: 'Concise summary of billable labor performed.',
        placeholderFallback: 'Completed electrical switchboard rewiring and fault diagnostic testing.',
        required: false,
      },
    ],
    completionMessage: 'Timesheet entry recorded with GPS timestamp.',
    completionAction: 'CLOCK_JOB_TIME',
  },
  {
    id: 'workflow_safety_audit',
    name: 'Site Safety & Hazard (JSA)',
    category: 'Safety & Compliance',
    description: 'Log pre-start safety checks, hazard identifications, and PPE compliance.',
    icon: 'ShieldAlert',
    triggerPhrases: ['safety check', 'hazard assessment', 'jsa', 'pre start', 'safety audit', 'swms', 'safety', 'hazards'],
    steps: [
      {
        id: 'hazards_detected',
        name: 'Hazards & Controls',
        prompt: 'Were any safety hazards identified on site, and what controls are in place?',
        type: 'FREE_TEXT_SUMMARY',
        extractionGoal: 'Extract identified hazards and risk controls.',
        placeholderFallback: 'Working near overhead power lines; spotter deployed and exclusion zone barricaded.',
        required: true,
      },
      {
        id: 'ppe_signoff',
        name: 'PPE & Compliance Sign-off',
        prompt: 'Confirm all required PPE is worn and site is safe to proceed?',
        type: 'YES_NO_QUESTION',
        extractionGoal: 'Determine YES or NO for safety compliance confirmation.',
        placeholderFallback: 'YES',
        required: true,
      },
    ],
    completionMessage: 'Safety compliance audit logged with GPS and timestamp.',
    completionAction: 'SAFETY_LOG',
  },
];
